const prefix = 'App/';

export const START_REFRESH_CONNECTED_PEOPLE = `${prefix}START_REFRESH_CONNECTED_PEOPLE`;
export const STOP_REFRESH_CONNECTED_PEOPLE = `${prefix}STOP_REFRESH_CONNECTED_PEOPLE`;

export const REFRESH_CONNECTED_PEOPLE_REQUEST = `${prefix}REFRESH_CONNECTED_PEOPLE_REQUEST`;
export const START_FETCH_CONNECTED_PEOPLE = `${prefix}START_FETCH_CONNECTED_PEOPLE`;
export const REFRESH_CONNECTED_PEOPLE_SUCCESS = `${prefix}REFRESH_CONNECTED_PEOPLE_SUCCESS`;
export const REFRESH_CONNECTED_PEOPLE_ERROR = `${prefix}REFRESH_CONNECTED_PEOPLE_ERROR`;
